-- Migration: performance_fixes_indexes
-- Performance improvements via index optimizations
-- Synced from cloud Supabase

CREATE UNIQUE INDEX IF NOT EXISTS admin_departments_name_key ON public.admin_departments USING btree (name);
CREATE UNIQUE INDEX IF NOT EXISTS admin_users_auth_user_id_key ON public.admin_users USING btree (auth_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS admin_users_email_key ON public.admin_users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_admin_users_department ON public.admin_users USING btree (department_id);
CREATE INDEX IF NOT EXISTS idx_admin_users_email ON public.admin_users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_banners_image_id ON public.banners USING btree (image_id);
CREATE UNIQUE INDEX IF NOT EXISTS cart_items_user_id_sku_id_key ON public.cart_items USING btree (user_id, sku_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_user_id ON public.cart_items USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_sku_id ON public.cart_items USING btree (sku_id);
CREATE INDEX IF NOT EXISTS idx_cdk_sku_map_cdk_id ON public.cdk_sku_map USING btree (cdk_id);
CREATE INDEX IF NOT EXISTS idx_cdk_sku_map_sku_id ON public.cdk_sku_map USING btree (sku_id);
CREATE UNIQUE INDEX IF NOT EXISTS cdks_code_key ON public.cdks USING btree (code);
CREATE INDEX IF NOT EXISTS idx_cdks_pre_order ON public.cdks USING btree (pre_order_id) WHERE (pre_order_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_cdks_product_status ON public.cdks USING btree (product_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS coupon_codes_code_key ON public.coupon_codes USING btree (code);
CREATE INDEX IF NOT EXISTS idx_coupon_codes_coupon_id ON public.coupon_codes USING btree (coupon_id);
CREATE INDEX IF NOT EXISTS idx_coupon_codes_status ON public.coupon_codes USING btree (status);
CREATE INDEX IF NOT EXISTS idx_coupon_codes_user_uid ON public.coupon_codes USING btree (user_uid);
CREATE INDEX IF NOT EXISTS idx_faqs_product_id ON public.faqs USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_faqs_category_id ON public.faqs USING btree (category_id);
CREATE UNIQUE INDEX IF NOT EXISTS image_categories_name_key ON public.image_categories USING btree (name);
CREATE INDEX IF NOT EXISTS idx_images_category_id ON public.images USING btree (category_id);
CREATE INDEX IF NOT EXISTS idx_messages_is_read ON public.messages USING btree (is_read);
CREATE INDEX IF NOT EXISTS idx_messages_type ON public.messages USING btree (type);
CREATE INDEX IF NOT EXISTS idx_messages_unread ON public.messages USING btree (user_uid, is_read) WHERE (is_read = false);
CREATE INDEX IF NOT EXISTS idx_messages_user_id ON public.messages USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_messages_user_uid ON public.messages USING btree (user_uid);
CREATE INDEX IF NOT EXISTS idx_fulfillments_order ON public.order_fulfillments USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_fulfillments_status ON public.order_fulfillments USING btree (status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_order_no ON public.orders USING btree (order_no);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders USING btree (status);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_pre_orders_expires ON public.pre_orders USING btree (status, expires_at);
CREATE INDEX IF NOT EXISTS idx_pre_orders_user ON public.pre_orders USING btree (user_id, status);
CREATE INDEX IF NOT EXISTS idx_pre_orders_user_id ON public.pre_orders USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_pre_orders_coupon_id ON public.pre_orders USING btree (coupon_id);
CREATE INDEX IF NOT EXISTS idx_pre_orders_related_order_id ON public.pre_orders USING btree (related_order_id);
CREATE INDEX IF NOT EXISTS idx_product_categories_sort ON public.product_categories USING btree (sort_order);
CREATE UNIQUE INDEX IF NOT EXISTS product_categories_name_key ON public.product_categories USING btree (name);
CREATE INDEX IF NOT EXISTS idx_psm_product ON public.product_sku_map USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_psm_sku ON public.product_sku_map USING btree (sku_id);
CREATE UNIQUE INDEX IF NOT EXISTS product_sku_map_product_id_sku_id_key ON public.product_sku_map USING btree (product_id, sku_id);
CREATE INDEX IF NOT EXISTS idx_skus_tag ON public.product_skus USING btree (tag);
CREATE INDEX IF NOT EXISTS idx_skus_type ON public.product_skus USING btree (product_type);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products USING btree (category_id);
CREATE INDEX IF NOT EXISTS idx_profiles_uid ON public.profiles USING btree (uid);
CREATE UNIQUE INDEX IF NOT EXISTS profiles_uid_key ON public.profiles USING btree (uid);
CREATE UNIQUE INDEX IF NOT EXISTS profiles_wechat_openid_key ON public.profiles USING btree (wechat_openid);
CREATE UNIQUE INDEX IF NOT EXISTS profiles_wechat_unionid_key ON public.profiles USING btree (wechat_unionid);
CREATE INDEX IF NOT EXISTS idx_profiles_wechat_openid ON public.profiles USING btree (wechat_openid) WHERE (wechat_openid IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_refund_requests_order_id ON public.refund_requests USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_refund_requests_status ON public.refund_requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_refund_requests_user_id ON public.refund_requests USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_refund_requests_admin_id ON public.refund_requests USING btree (admin_id);
CREATE INDEX IF NOT EXISTS idx_task_logs_executed ON public.scheduled_task_logs USING btree (executed_at DESC);
CREATE INDEX IF NOT EXISTS idx_slot_occupancies_cdk_status ON public.slot_occupancies USING btree (cdk_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_slot_occupancies_unique_occupied ON public.slot_occupancies USING btree (cdk_id, slot_index) WHERE ((status)::text = 'occupied'::text);
CREATE INDEX IF NOT EXISTS idx_slot_occupancies_pre_order_id ON public.slot_occupancies USING btree (pre_order_id);
CREATE INDEX IF NOT EXISTS idx_slot_occupancies_user_id ON public.slot_occupancies USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_id ON public.ticket_messages USING btree (ticket_id);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_sender_id ON public.ticket_messages USING btree (sender_id);
CREATE INDEX IF NOT EXISTS idx_tickets_order_id ON public.tickets USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON public.tickets USING btree (status);
CREATE INDEX IF NOT EXISTS idx_tickets_user_id ON public.tickets USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS tickets_ticket_no_key ON public.tickets USING btree (ticket_no);
CREATE INDEX IF NOT EXISTS idx_user_coupons_coupon_id ON public.user_coupons USING btree (coupon_id);
CREATE INDEX IF NOT EXISTS idx_user_coupons_expire_at ON public.user_coupons USING btree (expire_at);
CREATE INDEX IF NOT EXISTS idx_user_coupons_order_id ON public.user_coupons USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_user_coupons_redeemed_code ON public.user_coupons USING btree (user_id, redeemed_code);
CREATE INDEX IF NOT EXISTS idx_user_coupons_user_id ON public.user_coupons USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_favorites_product_id ON public.user_favorites USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_user_favorites_user_id ON public.user_favorites USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_favorites_user_id_product_id_sku_id_key ON public.user_favorites USING btree (user_id, product_id, sku_id);
CREATE INDEX IF NOT EXISTS idx_user_favorites_sku_id ON public.user_favorites USING btree (sku_id);
CREATE INDEX IF NOT EXISTS idx_wallet_transactions_user_id ON public.wallet_transactions USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS wechat_login_sessions_scene_str_key ON public.wechat_login_sessions USING btree (scene_str);
CREATE INDEX IF NOT EXISTS idx_wechat_login_sessions_scene ON public.wechat_login_sessions USING btree (scene_str);
CREATE INDEX IF NOT EXISTS idx_wechat_login_sessions_expires ON public.wechat_login_sessions USING btree (expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS channel_recognitions_channel_key_key ON public.channel_recognitions USING btree (channel_key);
CREATE INDEX IF NOT EXISTS idx_channel_recognitions_product_id ON public.channel_recognitions USING btree (product_id);
CREATE UNIQUE INDEX IF NOT EXISTS recharge_orders_out_trade_no_key ON public.recharge_orders USING btree (out_trade_no);
CREATE INDEX IF NOT EXISTS idx_recharge_orders_user_id ON public.recharge_orders USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_recharge_orders_status ON public.recharge_orders USING btree (status);
CREATE INDEX IF NOT EXISTS idx_recharge_orders_created_at ON public.recharge_orders USING btree (created_at DESC);
